version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: shotsync_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: shotsync
    ports:
      - "3306:3306"
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    networks:
      - shotsync-network

networks:
  shotsync-network:
    driver: bridge
